<?php
	$this->inlineScript()->appendFile('/dist/js/app/services/list.js')
		->appendFile('/dist/js/app/controllers/program/IndexCtrl.js');
?>
<div data-ng-controller="IndexCtrl"
    <?php echo $this->fzyNgInit()->addItems($this->viewModel()->getCurrent()->getVariables())?> >
	<div class="action-bar wrapper">
		<h1>Programs</h1>
		<!-- <div class="buttons">
			<a class="button primary" href="<?php echo $this->url('home/system/program', array('action' => 'new')) ?>">New Program</a>
		</div> -->
	</div>
    <div class="status-bar">
        <div class="msg wrapper"><p>{{ msgWrapperText }}</p></div>
    </div>
    <div id="filter-options-container" class="filter-options-container wrapper">
        <h2>Filter Options</h2>
        <span class="filter-category" data-ng-repeat="category in filters">
            <span class="filter-option" data-ng-repeat="filter in category">
                <span><strong>{{ filter.typeLabel }}:</strong> {{ filter.valueLabel }}</span><button href="#" data-ng-click="removeFilter(filter.type, filter.id)" aria-label="remove filter"></button>
            </span>
        </span>
    </div>
    <div class="wrapper programs-table">
        <div class="flyout-menu" id="filtersFlyout" data-ng-click="flyoutEvents($event)">
            <form name="programfilters" novalidate>
                <nav class="active" role="navigation" aria-label="Filters" >
                    <!-- Top level filter list -->
                    <div data-level="{{ panel.level }}">
                        <h3>{{ panel.getLabel() }}</h3>
                        <h4>Filter by</h4>
                        <ul ng-include src="panel.template"></ul>
                    </div>
                    <!-- template for filter menu -->
                    <script type="text/ng-template" id="list">
                                <li class="close-btn " data-ng-click="closeFilterPanel($event)" >
                                    <button href="#" aria-label="back"></button>
                                </li>
                                <li class="field" data-ng-if="panel.selectAll" >
                                    <input type="checkbox" data-ng-checked="getTempFilter(panel.parent.type, panel.id)" data-ng-click="setTempFilter(panel.parent.type, panel)" name="filter_{{ panel.parent.type }}_{{ panel.id }}" id="filter_{{ panel.parent.type }}_{{ panel.id }}">
                                    <label for="filter_{{ panel.parent.type }}_{{ panel.id }}">All {{ item.name }}</label>
                                </li>
                                <li data-ng-repeat="item in panel.items | filter: item.getCustomFilter()" data-ng-click="item.activatePanel($event)" data-ng-class="{'disabled': item.addDisabledClass()}">
                                    <a href="#" data-ng-click="item.loadPanel(item)">{{item.name}}<span data-ng-if="item.addDisabledClass()">{{ item.disabledLabel }}</span></a>
                                    <div data-level="{{ panel.level+1 }}" aria-label="{{ item.name }} Filters">
                                        <h3>{{ panel.getLabel() }}</h3>
                                        <h4>Filter by {{ item.name }}</h4>
                                        <ul ng-if="item.panel && item.panel.template" ng-include src="item.panel.template" onload="panel = getNextPanel(panel, item)"></ul>
                                    </div >
                                </li>
                                <li data-ng-hide="panel.items.length" class="loader">
                                    <span data-ng-hide="panel.loading">Load more...</span>
                                    <span>Loading <img src="/dist/img/select2/select2-spinner.gif" alt="Loading..." /></span>
                                </li>
                                <!-- Add an "Apply Filters" button to non-leaf panel if selectAll has been set on the panel and a filter has been chosen -->
                                <li ng-if="panel.selectAll" ng-show="getTempFilter(panel.parent.type, panel.id)">
                                    <button class="apply-filters-btn" data-ng-click="applyFilters(panel.parent.type)">Apply Filters</button>
                                </li>
                    </script>
                    <!-- template for default filter selection for filter leaf nodes -->
                    <script type="text/ng-template" id="filters">
                            <li class="close-btn" data-ng-click="closeFilterPanel($event)">
                                <button href="#" aria-label="back"></button>
                            </li>
                            <li>
                            <!-- <li data-ng-if="panel.recordsTotal > maxFiltersShown"> -->
                                <!-- Add combobox for searching through filter options here -->
                                <input type="text" data-ng-model="searchFilters[panel.type]" data-ng-model-options="{debounce: 500}" data-ng-change="panel.updateFiltersFromSearch()" name="searchfilter_{{ panel.type }}" placeholder="{{ panel.getSearchText() }}">
                            </li>
                            <li class ="field" data-ng-if="panel.selectAll" >
                                <input type="checkbox" data-ng-checked="getTempFilter(panel.parent.type, panel.id)" data-ng-click="setTempFilter(panel.parent.type, panel)" name="filter_{{ panel.parent.type }}_{{ panel.id }}" id="filter_{{ panel.parent.type }}_{{ panel.id }}">
                                <label for="filter_{{ panel.parent.type }}_{{ panel.id }}">All {{ item.name }}</label>
                            </li>
                            <li class="field" data-ng-repeat="item in panel.items track by item.id | filter: item.getCustomFilter()" data-ng-class="{'disabled': panel.addDisabledFilterClass()}">
                                <input type="checkbox" data-ng-disabled="panel.addDisabledFilterClass()" data-ng-checked="getTempFilter(panel.type, item.id)" data-ng-click="setTempFilter(panel.type, item)" name="filter_{{ panel.type }}_{{ item.id }}" id="filter_{{ panel.type }}_{{ item.id }}">
                                <label for="filter_{{ panel.type }}_{{ item.id }}">{{item.name}}</label>
                            </li>
                            <li data-ng-hide="panel.meta.total <= panel.items.length" data-ng-click="panel.loadMore()" class="loader">
                                <span data-ng-hide="panel.loading">Load more...</span>
                                <span data-ng-show="panel.loading">Loading <img src="/dist/img/select2/select2-spinner.gif" alt="Loading..." /></span>
                            </li>
                            <li data-ng-hide="getTempFilter(panel.parent.type, panel.id)">
                                <button class="apply-filters-btn" data-ng-click="applyFilters(panel.type)">Apply Filters</button>
                            </li>
                            <!-- Add an "Apply Filters" button to non-leaf panel if selectAll has been set on the panel and a filter has been chosen -->
                            <li ng-if="panel.selectAll" ng-show="getTempFilter(panel.parent.type, panel.id)">
                                <button class="apply-filters-btn" data-ng-click="applyFilters(panel.parent.type)">Apply Filters</button>
                            </li>
                    </script>
                    <!-- template for date filter selection -->
                    <script type="text/ng-template" id="date">
                        <li class="close-btn" data-ng-click="closeFilterPanel($event)">
                            <button href="#" aria-label="back"></button>
                        </li>
                        <li>
                            <input ui-date ng-model="dateFilters[panel.type]" placeholder="Enter a Date">
                        </li>
                        <li>
                            <button class="apply-filters-btn" data-ng-click="applyDateFilter(panel.type)">Apply Filters</button>
                        </li>
                    </script>
                </nav>
            </form>
        </div>
        <div class="rss-feeds">
            <button class="primary">Subscribe <span class="icon-feed"></span></button>
            <div class="rss-options">
                <a class="rss-all button primary" href="{{ subscribeToAllProgramsUrl }}">Subscribe to All-Programs Feed <span class="icon-feed"></span></a>
                <a class="state-all button primary" data-ng-show="hasFilterOfType('state')" href="{{ getStateRSSLink() }}">Subscribe to {{ getStateFilterAbbreviation() }} Programs Feed <span class="icon-feed"></span></a>
            </div>
        </div>
        <button data-ng-click="toggleFiltersDisplay()" class="btn-filters">Apply Filter <span class="icon-cog" aria-hidden="true"></span></button>
    	<table datatable="" dt-events dt-options="dtOptions" dt-columns="dtColumns" class="row-border hover"></table>
    </div>

</div>
