<div class="wrapper">
    <h1><?php echo $this->translate('Sign In'); ?></h1>

    <?php
    $form = $this->loginForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/login'));
    $form->setAttribute('method', 'post');
    ?>

    <?php echo $this->form()->openTag($form) ?>

    <section class="login animated fadeIn zend_form">
        <?php echo $this->formElementErrors($form->get('identity')) ?>

        <div class="field">
            <?php echo $this->formLabel($form->get('identity')) ?><br />
            <?php echo $this->formInput($form->get('identity')) ?>
        </div>
        <div class="field">
            <?php echo $this->formLabel($form->get('credential')) ?><br />
            <?php echo $this->formInput($form->get('credential')) ?>
        </div>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <div class="field"><?php echo $this->formButton($form->get('submit')->setAttribute('class','primary')) ?></div>
    </section>

    <?php echo $this->form()->closeTag() ?>

    
    <div>
        <?php echo $this->translate('Forgot your password?'); ?> <a href="<?php echo $this->url('fzyauth-password/forgot/get') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"> <?php echo $this->translate('Reset it!'); ?> </a>
    </div>
</div>